apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ocp-template
  annotations:
    description: "Template to deploy a customizable index.html file served by Nginx on OpenShift"
labels:
  app: ${APP_NAME}
objects:
  # ConfigMap to store index.html
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${APP_NAME}-content
      namespace: ${NAMESPACE}
    data:
      index.html: ${HTML_CONTENT}
  
  # configMap for Nginx configuration
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nginx-config
      namespace: ${NAMESPACE}
    data:
      nginx.conf: |
        user nginx;
        worker_processes auto;
        error_log /dev/stderr;
        pid /tmp/nginx.pid;
        events {
            worker_connections 1024;
        }
        http {
            include /etc/nginx/mime.types;
            default_type application/octet-stream;
            access_log /dev/stdout;
            sendfile on;
            keepalive_timeout 65;
            server {
                listen 80;
                server_name localhost;
                root /usr/share/nginx/html;
                location / {
                    try_files $uri $uri/ /index.html;
                }
            }
        }

  # Deployment for Nginx
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
    spec:
      replicas: ${{REPLICA_COUNT}}
      selector:
        matchLabels:
          app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - name: nginx
              image: ${NGINX_IMAGE}
              ports:
                - containerPort: ${{CONTAINER_PORT}}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
              volumeMounts:
                - name: html-content
                  mountPath: /usr/share/nginx/html/index.html
                  subPath: index.html
                - name: nginx-config
                  mountPath: /etc/nginx/nginx.conf
                  subPath: nginx.conf
          volumes:
            - name: html-content
              configMap:
                name: ${APP_NAME}-content
                items:
                  - key: index.html
                    path: index.html
            - name: nginx-config
              configMap:
                name: nginx-config
                items:
                  - key: nginx.conf
                    path: nginx.conf

  # Service to expose Nginx
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}-service
      namespace: ${NAMESPACE}
    spec:
      selector:
        app: ${APP_NAME}
      ports:
        - protocol: TCP
          port: ${{SERVICE_PORT}}
          targetPort: ${{CONTAINER_PORT}}
      type: ClusterIP

  # Route for external access
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${APP_NAME}-route
      namespace: ${NAMESPACE}
    spec:
      to:
        kind: Service
        name: ${APP_NAME}-service
      port:
        targetPort: ${{CONTAINER_PORT}}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
parameters:
  - name: APP_NAME
    description: "Name of the application"
    value: "nginx-html"
    required: true
  - name: REPLICA_COUNT
    description: "Number of pod replicas"
    value: "1"
    required: true
  - name: NAMESPACE
    description: "Namespace (project) to deploy the application"
    value: "dev"
  - name: NGINX_IMAGE
    description: "Nginx container image to use"
    value: "nginx:latest"
  - name: CONTAINER_PORT
    description: "Port the Nginx container listens on"
    value: "80"
  - name: SERVICE_PORT
    description: "Port exposed by the Service"
    value: "80"
  - name: HTML_CONTENT
    description: "Content of index.html file"
    value: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>Welcome to OpenShift Template application</title>
      </head>
      <body>
        <h1>Hello, OpenShift learners!</h1>
        <p>This is a simple webpage served by Nginx on OpenShift.</p>
      </body>
      </html>